# Generated by Django 2.2 on 2021-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='blogimages')),
            ],
        ),
    ]
